# Generated by Django 5.1.4 on 2024-12-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('exhibit_number', models.IntegerField()),
                ('exhibit_image', models.TextField(max_length=10)),
                ('original_language_text', models.TextField(max_length=1000)),
                ('english_language_text', models.TextField(max_length=1000)),
                ('spanish_language_text', models.TextField(max_length=1000)),
                ('portuguese_language_text', models.TextField(max_length=1000)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.institution')),
            ],
        ),
    ]
