# Generated by Django 5.1.4 on 2024-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exhibit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_image',
            field=models.TextField(max_length=1000),
        ),
    ]
