# Generated by Django 5.1.4 on 2024-12-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_institution_id_exhibit_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='institution',
            new_name='institution_id',
        ),
    ]
