# Generated by Django 5.1.4 on 2024-12-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_institution_id_exhibit_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
